mv AOSmith.png AOSMITH.png
mv AC_Pro.png ACPRO.png
mv Advantage.jpg ADVANTAGE.jpg
mv Allied.png ALLIED.png
mv American_Standard_Water_Heaters.png AMERICANSTANDARDWATERHEATERS.png
mv Arcoaire.jpeg ARCOAIRE.jpeg
mv Ariston.jpg ARISTON.jpg
mv Armstrong_Air.png ARMSTRONGAIR.png
mv Blueridge.png BLUERIDGE.png
mv Bosch.png BOSCH.png
mv Bradford_White.png BRADFORDWHITE.png
mv custom_comfort.webp CUSTOMCOMFORT.webp
mv geosmart_energy.webp GEOSMARTENERGY.webp
mv Gridless.png GRIDLESS.png
mv icp_commercial.webp ICPCOMMERCIAL.webp
mv Laars.jpeg LAARS.jpeg
mv reliance_water_heaters.jpg RELIANCEWATERHEATERS.jpg
mv saint_roch.png SAINTROCH.png
mv stream_33.png STREAM33.png
mv thermal_zone.png THERMALZONE.png
mv Utica_Boilers.jpg UTICABOILERS.jpg 